function: "all"
source_folder: "/home/xavier/repos/pcl_pcd_animator/speed-70/pcd"
xyzi_folder: "/home/xavier/repos/pcl_pcd_animator/speed-70/XYZI"
pose_folder: "/home/xavier/repos/pcl_pcd_animator/speed-70/pose"
transformed_folder: "/home/xavier/repos/pcl_pcd_animator/speed-70/transformed"